name: surf_flutter_summer_school_24
description: "Surf Flutter Summer School '24"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  shared_preferences: ^2.2.3
  collection: ^1.18.0
  flutter_bloc: ^8.1.6
  get_it: ^7.7.0
  dio: ^5.5.0+1
  cached_network_image: ^3.3.1
  image_picker: ^1.1.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  test:

  
flutter:  
  uses-material-design: true
  assets:  
    - assets/images/ 
